### ISSUE TITLE
Allow higher versions of Node.js

### ISSUE THREAD

**Issue by AndrewBarba** [officert/node-siftscience#1]
Currently yarn fails to install dependencies if the Node.js version is not exactly 6.10.3 as defined in the node-siftscience `package.json`. Can we update the engines dict to:

```
"engines": {
    "node": ">=6"
},
```

**Comment by AndrewBarba** [comment]
https://github.com/officert/node-siftscience/pull/2

**Comment by officert** [comment]
updated and published to NPM @ 0.0.17
thanks!
